### PR TITLE
Add harvesting-related fixture loading to invoke tasks

### PR DESCRIPTION
**Pull request by ricardogsilva**
This PR finalizes #271, making the `fixtures` invoke task also load the harvesting fixtures.

It also adds an entry to  `.gitignore` to ignore files named `docker-compose.override.yml`

### CODE REVIEW

**Review by giohappy — COMMENTED** [review]
@ricardogsilva I think we should touch geonode-project files the less as possible, otherwise it's hard to make alignments in the future (as I did recently). What about loading the specific fixture inside a specific task that would be easier to track?

**Comment by ricardogsilva** [comment]
@giohappy 

Can you be a bit more specific on what changes you'd prefer instead? Do you mean that I'd add an additional tasks file with just this task? If so, then I guess I'd still need to modify geonode-project specific functionality in order to have be loaded? Or maybe I did not understand you

**Comment by giohappy** [comment]
yes @ricardogsilva of course we need to change the geonode-project specific files but I would do it in a way that makes it easier to upgrade the files. Maybe moving the loading of specific fixtures to a specific task defined at the end of `tasks.py`

**Comment by meomancer** [comment]
hi @giohappy @ricardogsilva 
This PR is updated
is this correct approach @giohappy ?

**Pull request merged**
